# On parent server: install openssl and generate certs in /etc/ssl directory
# ENV=prod docker-compose up

version: '3.5'

services:

  postgres:
    image: postgres:11
    ports: 
      - 5432:5432
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - db/.env.${ENV}
    # environment:
    #   POSTGRES_HOST: 'example'
    #   POSTGRES_USER: 'example'
    #   POSTGRES_PASSWORD: 'example'
    #   POSTGRES_PORT: 5432
    #   POSTGRES_DATABASE: 'example'
  
  db_migrator:
    image: zbayindustries/chartman_db_migrator
    depends_on:
      - postgres
    ports:
      - 2999:2999
    environment:
      - ENV
    env_file:
      - db/.env.${ENV}
  
  nest:
    image: zbayindustries/chartman_nest
    ports: 
      - 3000:3000
    restart: always
    depends_on:
      - db_migrator
    environment:
      - ENV=${ENV}
    env_file:
      - ./server/.env.${ENV}
  
  frontend:
    image: zbayindustries/chartman_frontend
    ports: 
      - 80:80 
      - 443:443
    restart: always
    depends_on:
      - nest
    environment:
      - ENV
    volumes:
      - /etc/ssl:/etc/ssl
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/cors.conf:/etc/nginx/cors.conf
      - /var/log/nginx/:/var/log/nginx

volumes: 
  db-data: {}