version: '3.5'

services:

  postgres:
    image: postgres:11
    ports: 
      - 5433:5432
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - db/.env.${ENV}
    # environment:
    #   POSTGRES_HOST: 'example'
    #   POSTGRES_USER: 'example'
    #   POSTGRES_PASSWORD: 'example'
    #   POSTGRES_PORT: 5432
    #   POSTGRES_DATABASE: 'example'
  
  nest:
    image: zbayindustries/chartman_nest
    ports: 
      - 3000:3000
    restart: always
    depends_on:
      - db_migrator
    environment:
      - ENV=${ENV}
    env_file:
      - ./server/.env.${ENV}
  
  frontend:
    image: zbayindustries/chartman_frontend
    ports: 
      - 80:80 
      - 443:443
    restart: always
    depends_on:
      - nest
    environment:
      - ENV=${ENV}
    volumes:
      - /etc/ssl:/etc/ssl
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/cors.conf:/etc/nginx/cors.conf
      - /var/log/nginx/:/var/log/nginx
      - ./ng-env/environment.${ENV}.ts:/usr/src/app/src/environments/environment.prod.ts

volumes: 
  db-data: {}