version: '3.5'

services:

  postgres:
    image: postgres:11
    ports: 
      - 5433:5432
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - server/.env.test
    # environment:
    #   POSTGRES_HOST: 'example'
    #   POSTGRES_USER: 'example'
    #   POSTGRES_PASSWORD: 'example'
    #   POSTGRES_PORT: 5432
    #   POSTGRES_DB: 'example'
  
  nest:
    image: zbayindustries/chartman_nest
    ports: 
      - 3000:3000
    restart: always
    depends_on:
      - postgres
    environment:
      - ENV=test
    env_file:
      - ./server/.env.test
  
  frontend:
    image: zbayindustries/chartman_frontend
    ports: 
      - 80:80 
      - 443:443
    restart: always
    depends_on:
      - nest
    volumes:
      - /etc/ssl:/etc/ssl
      - ./nginx/nginx.test.conf:/etc/nginx/nginx.conf
      - ./nginx/cors.conf:/etc/nginx/cors.conf
      - /var/log/nginx/:/var/log/nginx

volumes: 
  db-data: {}