version: '3.5'

services:

  postgres:
    image: postgres:11
    ports: 
      - 5433:5432
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - server/.env.prod
    # environment:
    #   POSTGRES_HOST: 'example'
    #   POSTGRES_USER: 'example'
    #   POSTGRES_PASSWORD: 'example'
    #   POSTGRES_PORT: 5432
    #   POSTGRES_DB: 'example'
  
  nest:
    image: zbayindustries/chartman_nest
    ports: 
      - 3000:3000
    restart: always
    depends_on:
      - postgres
    environment:
      - ENV=prod
    env_file:
      - ./server/.env.prod
  
  frontend:
    image: zbayindustries/chartman_frontend
    ports: 
      - 80:80 
      - 443:443
    restart: always
    depends_on:
      - nest
    volumes:
      - /etc/ssl:/etc/ssl
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf
      - ./nginx/cors.conf:/etc/nginx/cors.conf
      - /var/log/nginx/:/var/log/nginx
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'" # Reload every 6 hrs in case SSL certs changed

  certbot:
    image: certbot/certbot
    depends_on:
      - frontend
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'" # Check for SSL renewal every 12 hrs

volumes: 
  db-data: {}